begin;

create extension if not exists pgcrypto;

create sequence if not exists public.registration_code_seq start with 128 increment by 1;
create sequence if not exists public.contact_code_seq start with 128 increment by 1;

create or replace function public.normalize_digits(value text)
returns text
language sql
immutable
as $$
  select translate(coalesce(value, ''), '۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩', '01234567890123456789');
$$;

create or replace function public.next_registration_tracking_code()
returns text
language sql
volatile
security definer
set search_path = public
as $$
  select 'AY-1405-' || lpad(nextval('public.registration_code_seq')::text, 5, '0');
$$;

create or replace function public.next_contact_request_code()
returns text
language sql
volatile
security definer
set search_path = public
as $$
  select 'تماس-' || lpad(nextval('public.contact_code_seq')::text, 4, '0');
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'مدیر سامانه',
  created_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  tracking_code text not null unique default public.next_registration_tracking_code(),
  full_name text not null,
  phone text not null,
  province text,
  city text,
  route text not null,
  axis text not null,
  issue text not null,
  experience_solution text,
  file_path text,
  form_data jsonb not null default '{}'::jsonb,
  status text not null default 'ثبت‌شده',
  admin_message text not null default 'پرونده با موفقیت دریافت شده است.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.registration_status_history (
  id bigint generated by default as identity primary key,
  registration_id uuid not null references public.registrations(id) on delete cascade,
  previous_status text,
  new_status text not null,
  message text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_requests (
  id uuid primary key default gen_random_uuid(),
  request_code text not null unique default public.next_contact_request_code(),
  full_name text not null,
  phone text not null,
  province text not null,
  city text not null,
  preferred_time text not null,
  subject text not null,
  note text,
  status text not null default 'جدید',
  internal_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_status_history (
  id bigint generated by default as identity primary key,
  contact_request_id uuid not null references public.contact_requests(id) on delete cascade,
  previous_status text,
  new_status text not null,
  internal_note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
create index if not exists registrations_status_idx on public.registrations(status);
create index if not exists registrations_phone_idx on public.registrations(phone);
create index if not exists contact_requests_created_at_idx on public.contact_requests(created_at desc);
create index if not exists contact_requests_status_idx on public.contact_requests(status);
create index if not exists contact_requests_phone_idx on public.contact_requests(phone);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.log_registration_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status
     or old.admin_message is distinct from new.admin_message then
    insert into public.registration_status_history (
      registration_id,
      previous_status,
      new_status,
      message,
      changed_by
    ) values (
      new.id,
      old.status,
      new.status,
      new.admin_message,
      auth.uid()
    );
  end if;
  return new;
end;
$$;

create or replace function public.log_contact_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status
     or old.internal_note is distinct from new.internal_note then
    insert into public.contact_status_history (
      contact_request_id,
      previous_status,
      new_status,
      internal_note,
      changed_by
    ) values (
      new.id,
      old.status,
      new.status,
      new.internal_note,
      auth.uid()
    );
  end if;
  return new;
end;
$$;

create or replace function public.set_setting_audit_fields()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists registrations_set_updated_at on public.registrations;
create trigger registrations_set_updated_at
before update on public.registrations
for each row execute function public.set_updated_at();

drop trigger if exists registrations_log_status on public.registrations;
create trigger registrations_log_status
after update on public.registrations
for each row execute function public.log_registration_status_change();

drop trigger if exists contact_requests_set_updated_at on public.contact_requests;
create trigger contact_requests_set_updated_at
before update on public.contact_requests
for each row execute function public.set_updated_at();

drop trigger if exists contact_requests_log_status on public.contact_requests;
create trigger contact_requests_log_status
after update on public.contact_requests
for each row execute function public.log_contact_status_change();

drop trigger if exists app_settings_set_audit on public.app_settings;
create trigger app_settings_set_audit
before insert or update on public.app_settings
for each row execute function public.set_setting_audit_fields();

alter table public.admin_users enable row level security;
alter table public.registrations enable row level security;
alter table public.registration_status_history enable row level security;
alter table public.contact_requests enable row level security;
alter table public.contact_status_history enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists admin_users_self_read on public.admin_users;
create policy admin_users_self_read
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists registrations_admin_all on public.registrations;
create policy registrations_admin_all
on public.registrations
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists registration_history_admin_read on public.registration_status_history;
create policy registration_history_admin_read
on public.registration_status_history
for select
to authenticated
using (public.is_admin());

drop policy if exists contacts_admin_all on public.contact_requests;
create policy contacts_admin_all
on public.contact_requests
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists contact_history_admin_read on public.contact_status_history;
create policy contact_history_admin_read
on public.contact_status_history
for select
to authenticated
using (public.is_admin());

drop policy if exists settings_admin_all on public.app_settings;
create policy settings_admin_all
on public.app_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.submit_registration(
  p_full_name text,
  p_phone text,
  p_province text,
  p_city text,
  p_route text,
  p_axis text,
  p_issue text,
  p_experience_solution text,
  p_file_path text,
  p_form_data jsonb
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_phone text;
  generated_code text;
begin
  normalized_phone := public.normalize_digits(p_phone);

  if length(trim(coalesce(p_full_name, ''))) < 2 then
    raise exception 'نام و نام خانوادگی معتبر نیست';
  end if;

  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس معتبر نیست';
  end if;

  if length(trim(coalesce(p_route, ''))) = 0
     or length(trim(coalesce(p_axis, ''))) = 0
     or length(trim(coalesce(p_issue, ''))) = 0 then
    raise exception 'اطلاعات مسیر و مسئله کامل نیست';
  end if;

  insert into public.registrations (
    full_name,
    phone,
    province,
    city,
    route,
    axis,
    issue,
    experience_solution,
    file_path,
    form_data
  ) values (
    trim(p_full_name),
    normalized_phone,
    nullif(trim(coalesce(p_province, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    trim(p_route),
    trim(p_axis),
    trim(p_issue),
    nullif(trim(coalesce(p_experience_solution, '')), ''),
    nullif(trim(coalesce(p_file_path, '')), ''),
    coalesce(p_form_data, '{}'::jsonb)
  )
  returning tracking_code into generated_code;

  return generated_code;
end;
$$;

create or replace function public.submit_contact_request(
  p_full_name text,
  p_phone text,
  p_province text,
  p_city text,
  p_preferred_time text,
  p_subject text,
  p_note text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_phone text;
  generated_code text;
begin
  normalized_phone := public.normalize_digits(p_phone);

  if length(trim(coalesce(p_full_name, ''))) < 2 then
    raise exception 'نام و نام خانوادگی معتبر نیست';
  end if;

  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس معتبر نیست';
  end if;

  if length(trim(coalesce(p_province, ''))) = 0
     or length(trim(coalesce(p_city, ''))) = 0
     or length(trim(coalesce(p_preferred_time, ''))) = 0
     or length(trim(coalesce(p_subject, ''))) = 0 then
    raise exception 'اطلاعات درخواست تماس کامل نیست';
  end if;

  insert into public.contact_requests (
    full_name,
    phone,
    province,
    city,
    preferred_time,
    subject,
    note
  ) values (
    trim(p_full_name),
    normalized_phone,
    trim(p_province),
    trim(p_city),
    trim(p_preferred_time),
    trim(p_subject),
    nullif(trim(coalesce(p_note, '')), '')
  )
  returning request_code into generated_code;

  return generated_code;
end;
$$;

create or replace function public.track_registration(
  p_tracking_code text,
  p_last4 text
)
returns table (
  tracking_code text,
  status text,
  admin_message text,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.tracking_code,
    r.status,
    r.admin_message,
    r.updated_at
  from public.registrations r
  where r.tracking_code = trim(p_tracking_code)
    and right(public.normalize_digits(r.phone), 4) = right(public.normalize_digits(p_last4), 4)
  limit 1;
$$;

create or replace function public.get_public_settings()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb)
  from public.app_settings
  where key like 'public.%';
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

revoke all on function public.submit_registration(text, text, text, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.submit_registration(text, text, text, text, text, text, text, text, text, jsonb) to anon, authenticated;

revoke all on function public.submit_contact_request(text, text, text, text, text, text, text) from public;
grant execute on function public.submit_contact_request(text, text, text, text, text, text, text) to anon, authenticated;

revoke all on function public.track_registration(text, text) from public;
grant execute on function public.track_registration(text, text) to anon, authenticated;

revoke all on function public.get_public_settings() from public;
grant execute on function public.get_public_settings() to anon, authenticated;

insert into public.app_settings (key, value)
values
  ('public.registration_enabled', 'true'::jsonb),
  ('public.tracking_enabled', 'true'::jsonb),
  ('public.contact_enabled', 'true'::jsonb),
  ('public.admin_message_enabled', 'true'::jsonb),
  ('public.hero_stats', '{"registrations":"۱۲۰۰+","solutions":"۳۵۰+","provinces":"۳۱","axes":"۵"}'::jsonb),
  ('admin.max_upload_bytes', '10485760'::jsonb),
  ('admin.allowed_file_extensions', '["rtf","doc","docx","pdf"]'::jsonb)
on conflict (key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'registration-files',
  'registration-files',
  false,
  10485760,
  array[
    'application/rtf',
    'text/rtf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/pdf'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists registration_files_public_upload on storage.objects;
create policy registration_files_public_upload
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'registration-files');

drop policy if exists registration_files_admin_read on storage.objects;
create policy registration_files_admin_read
on storage.objects
for select
to authenticated
using (bucket_id = 'registration-files' and public.is_admin());

drop policy if exists registration_files_admin_update on storage.objects;
create policy registration_files_admin_update
on storage.objects
for update
to authenticated
using (bucket_id = 'registration-files' and public.is_admin())
with check (bucket_id = 'registration-files' and public.is_admin());

drop policy if exists registration_files_admin_delete on storage.objects;
create policy registration_files_admin_delete
on storage.objects
for delete
to authenticated
using (bucket_id = 'registration-files' and public.is_admin());

commit;
