-- Public API abuse protection for registration, contact and tracking.
-- Applied to production Supabase on 2026-09-08.

create table if not exists public.public_rate_limit_attempts (
  id bigint generated by default as identity primary key,
  action text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists public_rate_limit_attempts_lookup_idx
  on public.public_rate_limit_attempts (action, key_hash, created_at desc);
create index if not exists public_rate_limit_attempts_created_at_idx
  on public.public_rate_limit_attempts (created_at);

alter table public.public_rate_limit_attempts enable row level security;
revoke all on table public.public_rate_limit_attempts from public, anon, authenticated;

create or replace function public.consume_public_rate_limit(
  p_action text,
  p_key text,
  p_limit integer,
  p_window interval,
  p_error_message text
)
returns void
language plpgsql
volatile
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_key_hash text;
  v_count integer;
begin
  if p_limit < 1 or p_window <= interval '0 seconds' then
    raise exception 'تنظیمات محدودیت درخواست نامعتبر است.';
  end if;

  v_key_hash := encode(digest(coalesce(p_key, ''), 'sha256'), 'hex');
  perform pg_advisory_xact_lock(hashtext(p_action || ':' || v_key_hash));

  select count(*)::integer into v_count
  from public.public_rate_limit_attempts
  where action = p_action
    and key_hash = v_key_hash
    and created_at >= now() - p_window;

  if v_count >= p_limit then
    raise exception '%', p_error_message;
  end if;

  insert into public.public_rate_limit_attempts(action, key_hash)
  values (p_action, v_key_hash);

  delete from public.public_rate_limit_attempts
  where created_at < now() - interval '2 days';
end;
$$;

revoke all on function public.consume_public_rate_limit(text,text,integer,interval,text)
  from public, anon, authenticated;

create or replace function public.registration_submission_allowed(p_phone text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  normalized_phone text;
  v_key_hash text;
  v_count integer;
begin
  if not public.public_setting_enabled('public.registration_enabled', true) then
    raise exception 'ثبت‌نام در حال حاضر غیرفعال است.';
  end if;

  normalized_phone := public.normalize_digits(p_phone);
  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس معتبر نیست';
  end if;

  v_key_hash := encode(digest(normalized_phone, 'sha256'), 'hex');
  select count(*)::integer into v_count
  from public.public_rate_limit_attempts
  where action = 'registration'
    and key_hash = v_key_hash
    and created_at >= now() - interval '24 hours';

  if v_count >= 3 then
    raise exception 'تعداد ثبت‌نام با این شماره بیش از حد مجاز است. لطفاً ۲۴ ساعت بعد دوباره تلاش کن.';
  end if;

  return true;
end;
$$;

revoke all on function public.registration_submission_allowed(text) from public;
grant execute on function public.registration_submission_allowed(text) to anon, authenticated;

create or replace function public.submit_registration(
  p_full_name text,
  p_phone text,
  p_province text,
  p_city text,
  p_route text,
  p_axis text,
  p_issue text,
  p_experience_solution text,
  p_file_path text,
  p_form_data jsonb
)
returns text
language plpgsql
volatile
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  normalized_phone text;
  generated_code text;
begin
  if not public.public_setting_enabled('public.registration_enabled', true) then
    raise exception 'ثبت‌نام در حال حاضر غیرفعال است.';
  end if;

  normalized_phone := public.normalize_digits(p_phone);

  if length(trim(coalesce(p_full_name, ''))) < 2 then
    raise exception 'نام و نام خانوادگی معتبر نیست';
  end if;
  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس معتبر نیست';
  end if;
  if length(trim(coalesce(p_route, ''))) = 0
     or length(trim(coalesce(p_axis, ''))) = 0
     or length(trim(coalesce(p_issue, ''))) = 0 then
    raise exception 'اطلاعات مسیر و مسئله کامل نیست';
  end if;

  perform public.consume_public_rate_limit(
    'registration', normalized_phone, 3, interval '24 hours',
    'تعداد ثبت‌نام با این شماره بیش از حد مجاز است. لطفاً ۲۴ ساعت بعد دوباره تلاش کن.'
  );

  insert into public.registrations (
    full_name, phone, province, city, route, axis, issue,
    experience_solution, file_path, form_data
  ) values (
    trim(p_full_name), normalized_phone,
    nullif(trim(coalesce(p_province, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    trim(p_route), trim(p_axis), trim(p_issue),
    nullif(trim(coalesce(p_experience_solution, '')), ''),
    nullif(trim(coalesce(p_file_path, '')), ''),
    coalesce(p_form_data, '{}'::jsonb)
  )
  returning tracking_code into generated_code;

  return generated_code;
end;
$$;

create or replace function public.submit_contact_request(
  p_full_name text,
  p_phone text,
  p_province text,
  p_city text,
  p_preferred_time text,
  p_subject text,
  p_note text
)
returns text
language plpgsql
volatile
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  normalized_phone text;
  generated_code text;
begin
  if not public.public_setting_enabled('public.contact_enabled', true) then
    raise exception 'فرم تماس با دبیرخانه در حال حاضر غیرفعال است.';
  end if;

  normalized_phone := public.normalize_digits(p_phone);

  if length(trim(coalesce(p_full_name, ''))) < 2 then
    raise exception 'نام و نام خانوادگی معتبر نیست';
  end if;
  if normalized_phone !~ '^09[0-9]{9}$' then
    raise exception 'شماره تماس معتبر نیست';
  end if;
  if length(trim(coalesce(p_province, ''))) = 0
     or length(trim(coalesce(p_city, ''))) = 0
     or length(trim(coalesce(p_preferred_time, ''))) = 0
     or length(trim(coalesce(p_subject, ''))) = 0 then
    raise exception 'اطلاعات درخواست تماس کامل نیست';
  end if;

  perform public.consume_public_rate_limit(
    'contact', normalized_phone, 5, interval '24 hours',
    'تعداد درخواست تماس با این شماره بیش از حد مجاز است. لطفاً ۲۴ ساعت بعد دوباره تلاش کن.'
  );

  insert into public.contact_requests (
    full_name, phone, province, city, preferred_time, subject, note
  ) values (
    trim(p_full_name), normalized_phone, trim(p_province), trim(p_city),
    trim(p_preferred_time), trim(p_subject), nullif(trim(coalesce(p_note, '')), '')
  )
  returning request_code into generated_code;

  return generated_code;
end;
$$;

create or replace function public.track_registration(
  p_tracking_code text,
  p_last4 text
)
returns table (
  tracking_code text,
  status text,
  admin_message text,
  updated_at timestamptz
)
language plpgsql
volatile
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_code text;
  v_last4 text;
begin
  if not public.public_setting_enabled('public.tracking_enabled', true) then
    raise exception 'پیگیری ثبت‌نام در حال حاضر غیرفعال است.';
  end if;

  v_code := upper(trim(coalesce(p_tracking_code, '')));
  v_last4 := right(public.normalize_digits(p_last4), 4);

  if v_code !~ '^AY-[0-9]{4}-[0-9]{5}$' or v_last4 !~ '^[0-9]{4}$' then
    raise exception 'کد پیگیری یا ۴ رقم آخر شماره موبایل معتبر نیست.';
  end if;

  perform public.consume_public_rate_limit(
    'tracking_pair', v_code || ':' || v_last4, 10, interval '15 minutes',
    'تعداد تلاش برای پیگیری بیش از حد مجاز است. لطفاً ۱۵ دقیقه بعد دوباره تلاش کن.'
  );
  perform public.consume_public_rate_limit(
    'tracking_code', v_code, 20, interval '15 minutes',
    'تعداد تلاش برای این کد پیگیری بیش از حد مجاز است. لطفاً ۱۵ دقیقه بعد دوباره تلاش کن.'
  );

  return query
  select
    r.tracking_code,
    r.status,
    case when public.public_setting_enabled('public.admin_message_enabled', true)
      then r.admin_message else ''::text end,
    r.updated_at
  from public.registrations r
  where r.tracking_code = v_code
    and right(public.normalize_digits(r.phone), 4) = v_last4
  limit 1;
end;
$$;

revoke all on function public.submit_registration(text,text,text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.submit_registration(text,text,text,text,text,text,text,text,text,jsonb) to anon, authenticated;
revoke all on function public.submit_contact_request(text,text,text,text,text,text,text) from public;
grant execute on function public.submit_contact_request(text,text,text,text,text,text,text) to anon, authenticated;
revoke all on function public.track_registration(text,text) from public;
grant execute on function public.track_registration(text,text) to anon, authenticated;
